source 'http://rubygems.org'

gem 'heroku'
gem 'execjs', '1.2.9'
gem 'therubyracer', '0.9.8'
gem 'coffee-script-source', '1.1.2'
gem 'coffee-script', '2.2.0'
gem 'uglifier', '1.0.4'
gem 'i18n', '0.6.0'
gem 'activesupport', '3.1.1'
